
services:
  app1:
    build: .
    ports:
      - "3001:3000"
    restart: always
    env_file:
      - .env

  app2:
    build: .
    ports:
      - "3002:3000"
    restart: always
    env_file:
      - .env

  app3:
    build: .
    ports:
      - "3003:3000"
    restart: always
    env_file:
      - .env